#spring.application.name=ecommerce
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test

#actuator
# management.endpoints.web.exposure.include=*
# endpoint.health.show-details: always

# Postgres configuration
#spring.datasource=url:
#spring.datasource=username:
#spring.datasource=password:
#e.t.c

spring:
  application:
    name: ecommerce
  datasource:
    url: jdbc:postgresql://localhost:5433/ecomdb
    username: twinners
    password: Danlard8576
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create

management:
  endpoints:
    web:
      exposure:
        include: beans, health
  endpoint:
    health:
      show-details: always
      #shutdown configuration
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

server:
  shutdown: graceful

info:
  app:
    name: MyNewApp
    description: App built by us
    version: 1.0.0

