#spring.application.name=ecommerce
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test

spring:
  application:
    name: ecommerce
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
