spring:
  application:
    name: user-service

  data:
    mongodb:
      uri: mongodb+srv://twinners:XGfrhAMeUlMQQnY2@user-data.dyqbypi.mongodb.net/userdb?retryWrites=true&w=majority
      database: userdb

server:
  port: 8082
