spring:
  application:
    name: user-service

  data:
    mongodb:
      uri: mongodb+srv://twinners:XGfrhAMeUlMQQnY2@user-data.dyqbypi.mongodb.net/userdb?retryWrites=true&w=majority&tls=true&tlsProtocol=TLSv1.2

server:
  port: 8082
