spring:
  application:
    name: user-service

  data:
    mongodb:
      uri: mongodb://localhost/:27017/userdb
      database: userdb

#  datasource:
#    url: jdbc:postgresql://localhost:5433/userdb
#    username: twinners
#    password: Danlard8576
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#
#  jpa:
#    database: postgresql
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create

server:
  port: 8082
